# Generated by Django 4.1.4 on 2022-12-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_pelicula_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Genero de la película'),
        ),
    ]
