# Generated by Django 4.1.4 on 2023-01-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0008_pelicula_descripcion_alter_director_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='año',
            field=models.DateField(null=True, verbose_name='Año de la película'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.DurationField(null=True, verbose_name='Duración de la películas'),
        ),
    ]
