# Generated by Django 4.1.4 on 2023-01-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0009_pelicula_año_pelicula_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.TimeField(null=True, verbose_name='Duración de la película'),
        ),
    ]
