# Generated by Django 4.1.4 on 2023-01-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0010_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='año',
            field=models.IntegerField(null=True, verbose_name='Año de la película'),
        ),
    ]
