# Generated by Django 4.1.4 on 2023-01-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0011_alter_pelicula_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='duracion',
            new_name='tiempo',
        ),
    ]
